version: "3"

services:
  iim:
    container_name: iim
    restart: on-failure
    build:
      context: .
      dockerfile: docker/node/dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development